version: "3"
services:
  dev-preview-${COMMIT_REF_NAME}:
    container_name: dev-preview-${COMMIT_REF_NAME}
    build:
      context: .
    labels:
      - traefik.http.routers.dev-preview-${COMMIT_REF_NAME}.rule=Host(`${COMMIT_REF_NAME}.dev.demo.com`)
      - traefik.http.routers.dev-preview-${COMMIT_REF_NAME}.tls=true
      - traefik.http.routers.dev-preview-${COMMIT_REF_NAME}.tls.certresolver=le

networks:
  external:
    name: traefik_default