version: "3"

networks:
  traefik-proxy-network:
    # 此处不用设置 external，因为是由本组合（compose 文件）创建的 network
    # external: true # 使用已存在、组合（compose 文件）之外的 network，如果不存在则提示 network proxy-net declared as external, but could not be found
    name: proxy-net # 指定名称
    
services:
  traefik:
    image: traefik:v2.5
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # 也可以注释 不开放仪表盘
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml # traefik 配置
      - ./acme.json:/acme.json # 维护证书信息--证书解析配置
      - ./log:/log # 日志文件夹挂载，这样可以在宿主机中直接查看日志
      - /var/run/docker.sock:/var/run/docker.sock # 使得 traefik 可以监听 docker 事件
    container_name: traefik
    networks: # 指定 network 使这个容器成为该网络的一部分
      - traefik-proxy-network
    # env_file: .env # 环境变量以文件形式进行存储配置 https://docs.docker.com/compose/env-file/
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.demo.com`)" # 也可以自身设置label 用于 traefik 发现并监控
      - "traefik.http.routers.api.service=api@internal" # 指定 api@internal 服务，开启 api 控制。
      