name: environment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  environment:
    runs-on: ubuntu-latest
    environment:
      name: production_environment
      url: https://github.com

    steps:
      - uses: actions/checkout@v3

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
    
        





