# This is a basic workflow to help you get started with Actions

name: env

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  env:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # 如何在 Github Actions 中设置环境变量
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
      
      - run: echo $KEY
        env:
          KEY: demo

      - run: echo $GITHUB_ENV 
          
      - run: echo "KEY1=$(echo key1)" >> $GITHUB_ENV
          
      - run: echo $KEY1
      
      - run: echo $CI
      
      - run: echo $GITHUB_REPOSITORY
      
      - run: echo $GITHUB_EVENT_NAME
      
      - run: echo $GITHUB_SHA
      
      - run: echo $GITHUB_REF_NAME
      
      - run: echo $GITHUB_HEAD_REF
      
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'





