name: Preview

# 执行 CI 的时机: 当提交 PR 到 main 分支时
on:
  pull_request:
    types:
      # 当新建了一个 PR 时
      - opened
      # 当提交 PR 的分支，未合并前并拥有新的 Commit 时
      - synchronize
    branches:    
      - main # 只监听主分支
  workflow_dispatch:

# 执行所有的 jobs
jobs:
  preview:
    # 该 Job 在自建的 Runner 中执行
    runs-on: self-hosted
    environment:
      # 获取 CICD 中的变量: Context
      # https://docs.github.com/en/actions/learn-github-actions/expressions
      name: preview/${{ github.head_ref }}
      url: https://${SERVICE_ADDRESS}/${{ github.head_ref }} 
    env:
      SERVICE_ADDRESS: ${{ secrets.SERVICE_ADDRESS }}
    steps:
      # 切出代码，使用该 Action 将可以拉取最新代码
      - uses: actions/checkout@v2
      - name: Preview
        run: |
          cat preview.docker-compose.yaml | envsubst > docker-compose.yaml
          cat preview.nginx.conf | envsubst > nginx.conf
          docker compose up --build -d dev-preview-${COMMIT_REF_NAME}
        env:
          COMMIT_REF_NAME: ${{ github.head_ref }}
          
